In [10]:
import numpy as np

R = np.array([
    [-1/np.sqrt(2),  1/np.sqrt(2),  0],
    [-1/2,          -1/2,           1/np.sqrt(2)],
    [1/2,           1/2,            1/np.sqrt(2)]
])

det_R = np.linalg.det(R)
print(f"Determinant of R: {det_R}")
if not np.isclose(det_R, 1):
    print("The matrix is not a valid rotation matrix (determinant is not 1).")
else:
    print("The matrix is a valid rotation matrix (determinant is 1).")

R_transpose = np.transpose(R)
identity_check = np.dot(R_transpose, R)
print(f"R^T * R:\n{identity_check}")
if not np.allclose(identity_check, np.eye(3)):
    print("The matrix is not a valid rotation matrix (R^T * R != I).")
else:
    print("The matrix is a valid rotation matrix (R^T * R = I).")

beta = np.arccos(R[2, 2])
print(f"beta = {beta} radians or {np.degrees(beta)} degrees")

if not np.isclose(np.sin(beta), 0):
    alpha = np.arctan2(R[2, 0], -R[2, 1])
    print(f"alpha = {alpha} radians or {np.degrees(alpha)} degrees")
else:
    alpha = 0
    print("Special case: beta is 0 or pi, alpha is set to 0.")

if not np.isclose(np.sin(beta), 0):
    gamma = np.arctan2(R[0, 2], R[1, 2])
    print(f"gamma = {gamma} radians or {np.degrees(gamma)} degrees")
else:
    gamma = 0
    print("Special case: beta is 0 or pi, gamma is set to 0.")

print(f"\nFinal ZXZ Euler angles (in radians):")
print(f"alpha = {alpha}")
print(f"beta = {beta}")
print(f"gamma = {gamma}")

print(f"\nFinal ZXZ Euler angles (in degrees):")
print(f"alpha = {np.degrees(alpha)}°")
print(f"beta = {np.degrees(beta)}°")
print(f"gamma = {np.degrees(gamma)}°")


Determinant of R: 0.9999999999999999
The matrix is a valid rotation matrix (determinant is 1).
R^T * R:
[[1.00000000e+00 1.11022302e-16 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
The matrix is a valid rotation matrix (R^T * R = I).
beta = 0.7853981633974484 radians or 45.00000000000001 degrees
alpha = 2.356194490192345 radians or 135.0 degrees
gamma = 0.0 radians or 0.0 degrees

Final ZXZ Euler angles (in radians):
alpha = 2.356194490192345
beta = 0.7853981633974484
gamma = 0.0

Final ZXZ Euler angles (in degrees):
alpha = 135.0°
beta = 45.00000000000001°
gamma = 0.0°


In [9]:
R

array([[-0.70710678,  0.70710678,  0.        ],
       [-0.5       , -0.5       ,  0.70710678],
       [ 0.5       ,  0.5       ,  0.70710678]])